rgbi = getDirectory("image");
ch1i = getDirectory("image");

open(rgbi);
rgb = getTitle();
open(ch1i);
ch1 = getTitle();
selectWindow(rgb);
run("Split Channels");
selectWindow(rgb + " (blue)");
close();
selectWindow(rgb + " (green)");
close();
selectWindow(rgb + " (red)");
run("Gaussian Blur...", "sigma=2");
selectWindow(ch1);
run("Gaussian Blur...", "sigma=2");
run("Invert");
imageCalculator("Divide create", ch1,rgb+" (red)");
selectWindow(ch1);
setAutoThreshold("Default dark");
//run("Threshold...");
setAutoThreshold("Huang");
setOption("BlackBackground", false);
run("Convert to Mask");
run("Create Selection");
run("Make Inverse");
roiManager("Add");
selectWindow("Result of "+ch1);
roiManager("Select", 0);
setForegroundColor(0, 0, 0);
run("Fill", "slice");
run("Select None");
run("Fire");
